#!/usr/bin/env python3
"""
MITRE ATT&CK Coverage Report Generator
=======================================
Baca semua Sigma rules, extract MITRE ATT&CK tags,
generate Markdown coverage report.
"""

import yaml
from pathlib import Path
from collections import defaultdict
from datetime import datetime

RULES_DIR = Path(__file__).parent.parent / "rules"
OUTPUT_FILE = Path(__file__).parent.parent / "docs" / "coverage-report.md"

# MITRE ATT&CK tactics (simplified)
TACTICS = {
    "reconnaissance": "TA0043",
    "resource_development": "TA0042",
    "initial_access": "TA0001",
    "execution": "TA0002",
    "persistence": "TA0003",
    "privilege_escalation": "TA0004",
    "defense_evasion": "TA0005",
    "credential_access": "TA0006",
    "discovery": "TA0007",
    "lateral_movement": "TA0008",
    "collection": "TA0009",
    "command_and_control": "TA0011",
    "exfiltration": "TA0010",
    "impact": "TA0040",
}


def load_all_rules():
    rules = []
    for f in sorted(RULES_DIR.rglob("*.yml")):
        try:
            with open(f) as fh:
                rule = yaml.safe_load(fh)
            rule["_file"] = str(f.relative_to(RULES_DIR.parent))
            rules.append(rule)
        except Exception as e:
            print(f"[WARN] Cannot load {f.name}: {e}")
    return rules


def extract_mitre_tags(rule):
    tags = rule.get("tags", [])
    tactics = set()
    techniques = set()

    for tag in tags:
        tag = tag.lower().replace("attack.", "")
        if tag in TACTICS:
            tactics.add(tag)
        elif tag.startswith("t") and len(tag) >= 5:
            techniques.add(tag.upper())

    return tactics, techniques


def generate_coverage_report(rules):
    # Map technique -> list of rule files
    coverage = defaultdict(list)
    tactic_coverage = defaultdict(list)

    for rule in rules:
        tactics, techniques = extract_mitre_tags(rule)
        filepath = rule["_file"]

        for t in tactics:
            tactic_coverage[t].append(filepath)
        for tech in techniques:
            coverage[tech].append(filepath)

    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    total_rules = len(rules)
    covered_techniques = len(coverage)
    covered_tactics = len(tactic_coverage)

    report = f"""# MITRE ATT&CK Coverage Report

> Generated: {now}
> Total Rules: {total_rules}
> Covered Techniques: {covered_techniques}
> Covered Tactics: {covered_tactics}

---

## Coverage Summary

| Tactic | Technique | Rule |
|---|---|---|
"""

    for tactic, tactic_id in sorted(TACTICS.items()):
        tactic_rules = tactic_coverage.get(tactic, [])
        if tactic_rules:
            for r in tactic_rules:
                report += f"| {tactic.replace('_', ' ').title()} ({tactic_id}) | - | `{r}` |\n"
        else:
            report += f"| {tactic.replace('_', ' ').title()} ({tactic_id}) | ❌ No rules | - |\n"

    report += f"""
---

## Technique-Level Coverage

| Technique | Rules |
|---|---|
"""

    for tech in sorted(coverage.keys()):
        rules_list = ", ".join(f"`{r}`" for r in coverage[tech])
        report += f"| {tech} | {rules_list} |\n"

    # Coverage gaps
    uncovered = [t for t in TACTICS if t not in tactic_coverage]
    report += f"""
---

## Coverage Gaps ⚠️

"""

    if uncovered:
        report += "The following MITRE ATT&CK tactics have **zero detection rules**:\n\n"
        for t in uncovered:
            report += f"- ❌ **{t.replace('_', ' ').title()}** ({TACTICS[t]})\n"
    else:
        report += "✅ All 14 MITRE ATT&CK tactics have at least 1 detection rule!\n"

    report += f"""
---

## Top Rules by Coverage

| Rule | Techniques Covered | Level |
|---|---|---|
"""

    for rule in sorted(rules, key=lambda r: len(extract_mitre_tags(r)[1]), reverse=True)[:10]:
        _, techs = extract_mitre_tags(rule)
        report += f"| `{rule['_file']}` | {len(techs)} | {rule.get('level', 'N/A')} |\n"

    report += f"""
---

*Report generated by Detection-as-Code Pipeline*
"""
    return report


def main():
    print("=" * 60)
    print("  MITRE ATT&CK Coverage Report Generator")
    print("=" * 60)

    rules = load_all_rules()
    print(f"\n[+] Loaded {len(rules)} rules")

    report = generate_coverage_report(rules)

    OUTPUT_FILE.parent.mkdir(exist_ok=True)
    with open(OUTPUT_FILE, "w") as f:
        f.write(report)

    print(f"[+] Report saved: {OUTPUT_FILE}")

    # Print summary
    tactics_covered = set()
    for rule in rules:
        t, _ = extract_mitre_tags(rule)
        tactics_covered |= t

    print(f"[+] Tactics covered: {len(tactics_covered)}/14")
    print(f"[+] Tactics missing: {14 - len(tactics_covered)}")
    print("=" * 60)


if __name__ == "__main__":
    main()
