#!/usr/bin/env python3
from collections import defaultdict
"""
Rule Quality Checker
====================
Baca semua Sigma rules, assign quality score (0-100) berdasarkan:
- Metadata completeness (title, id, author, date, description, tags)
- False positive documentation
- MITRE ATT&CK mapping
- Level assignment
- Status (experimental vs stable)
"""

import yaml
from pathlib import Path
from datetime import datetime

RULES_DIR = Path(__file__).parent.parent / "rules"
OUTPUT_FILE = Path(__file__).parent.parent / "docs" / "quality-report.md"

REQUIRED_FIELDS = ["title", "id", "status", "description", "author", "date", "tags", "logsource", "detection", "level"]


def load_all_rules():
    rules = []
    for f in sorted(RULES_DIR.rglob("*.yml")):
        try:
            with open(f) as fh:
                rule = yaml.safe_load(fh)
            rule["_file"] = str(f.relative_to(RULES_DIR.parent))
            rule["_filename"] = f.name
            rules.append(rule)
        except Exception as e:
            print(f"[WARN] Cannot load {f.name}: {e}")
    return rules


def score_rule(rule):
    score = 0
    max_score = 100
    issues = []

    # 1. Required fields (30 pts)
    missing_fields = [f for f in REQUIRED_FIELDS if f not in rule]
    field_score = max(0, 30 - len(missing_fields) * 5)
    score += field_score
    if missing_fields:
        issues.append(f"Missing fields: {', '.join(missing_fields)}")

    # 2. MITRE ATT&CK mapping (25 pts)
    tags = rule.get("tags", [])
    has_tactic = any(not t.startswith("attack.t") for t in tags if t.startswith("attack."))
    has_technique = any(t.startswith("attack.t") for t in tags)

    if has_tactic and has_technique:
        score += 25
    elif has_technique:
        score += 15
        issues.append("Missing MITRE tactic tag")
    elif has_tactic:
        score += 10
        issues.append("Missing MITRE technique tag")
    else:
        score += 0
        issues.append("No MITRE ATT&CK tags")

    # 3. False positive documentation (15 pts)
    fp = rule.get("falsepositives", [])
    if fp and fp != ["Unknown"] and len(fp) > 0:
        score += 15
    else:
        score += 0
        issues.append("Missing falsepositives")

    # 4. Description quality (10 pts)
    desc = rule.get("description", "")
    if len(desc) > 80:
        score += 10
    elif len(desc) > 20:
        score += 5
        issues.append("Description too short")
    else:
        score += 0
        issues.append("Missing description")

    # 5. References (10 pts)
    refs = rule.get("references", [])
    if refs and len(refs) > 0:
        score += 10
    else:
        score += 0
        issues.append("No references")

    # 6. Status (10 pts)
    status = rule.get("status", "")
    if status == "stable":
        score += 10
    elif status == "test":
        score += 7
    elif status == "experimental":
        score += 5
    else:
        score += 0
        issues.append(f"Unknown status: {status}")

    grade = "A" if score >= 85 else "B" if score >= 70 else "C" if score >= 50 else "D"
    return score, grade, issues


def generate_quality_report(rules):
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    results = []

    for rule in rules:
        score, grade, issues = score_rule(rule)
        results.append((rule, score, grade, issues))

    avg_score = sum(r[1] for r in results) / len(results) if results else 0

    report = f"""# Rule Quality Report

> Generated: {now}
> Total Rules: {len(rules)}
> Average Score: {avg_score:.1f}/100

---

## Overall Quality

| Metric | Value |
|---|---|
| Total Rules | {len(rules)} |
| Average Score | {avg_score:.1f}/100 |
| A-grade (>85) | {sum(1 for r in results if r[2] == 'A')} |
| B-grade (70-84) | {sum(1 for r in results if r[2] == 'B')} |
| C-grade (50-69) | {sum(1 for r in results if r[2] == 'C')} |
| D-grade (<50) | {sum(1 for r in results if r[2] == 'D')} |

---

## Per-Rule Quality

| Rule | Score | Grade | Issues |
|---|---|---|---|
"""

    for rule, score, grade, issues in sorted(results, key=lambda r: r[1], reverse=True):
        filepath = rule["_file"]
        issues_str = ", ".join(issues) if issues else "✅ None"
        report += f"| `{filepath}` | {score}/100 | {grade} | {issues_str} |\n"

    report += f"""
---

## Common Issues

"""

    all_issues = defaultdict(int)
    for _, _, _, issues in results:
        for issue in issues:
            all_issues[issue] += 1

    if all_issues:
        for issue, count in sorted(all_issues.items(), key=lambda x: x[1], reverse=True):
            report += f"- **{issue}** — {count} rule(s)\n"
    else:
        report += "✅ All rules are high quality!\n"

    report += f"""
---

*Report generated by Detection-as-Code Pipeline*
"""
    return report


def main():
    print("=" * 60)
    print("  Rule Quality Checker")
    print("=" * 60)

    rules = load_all_rules()
    print(f"\n[+] Loaded {len(rules)} rules")

    report = generate_quality_report(rules)

    OUTPUT_FILE.parent.mkdir(exist_ok=True)
    with open(OUTPUT_FILE, "w") as f:
        f.write(report)

    print(f"[+] Report saved: {OUTPUT_FILE}")

    # Summary
    scores = [score_rule(r)[0] for r in rules]
    avg = sum(scores) / len(scores) if scores else 0
    print(f"[+] Average score: {avg:.1f}/100")
    print(f"[+] A-grade: {sum(1 for s in scores if s >= 85)}")
    print(f"[+] B-grade: {sum(1 for s in scores if 70 <= s < 85)}")
    print(f"[+] C-grade: {sum(1 for s in scores if 50 <= s < 70)}")
    print(f"[+] D-grade: {sum(1 for s in scores if s < 50)}")
    print("=" * 60)


if __name__ == "__main__":
    main()
